### ISSUE TITLE
Possible typo in telemetry parsing?

### ISSUE THREAD

**Issue by daniestevez** [danalvarez/gr-quetzal1#2]
Hi,

I'm reviewing the telemetry parser, since I'll soon be adding a [construct](https://construct.readthedocs.io/)-based telemetry parser for Quetzal-1 to the future gr-satellites v3.

I found what might be a typo in the telemetry conversion equations for the Z-axis of the magnetometer:

https://github.com/danalvarez/gr-quetzal1/blob/58c6b2f8da96d1104d05294673fa47329a5e8ba8/apps/quetzal1_parse.py#L391

Note the number `625`. The X- and Y- axes use `325` instead. Is this a typo or is the conversion factor really different for the Z-axis?

**Comment by danalvarez** [comment]
Hello! Great to hear you'll include a parser. We're very happy to hear that. No, it is actually different because we wanted greater resolution in the Z axis. So the value `625` is correct for the `Z` axis.

**Comment by daniestevez** [comment]
Thanks!
