### ISSUE TITLE
Wrong state of health parsing

### ISSUE THREAD

**Issue by mlenczyk** [danalvarez/gr-quetzal1#3]
https://github.com/danalvarez/gr-quetzal1/blob/master/apps/quetzal1_parse.py

At line 315 and 317 you have basically the same code. Looks like lack of parsing in else.

**Comment by danalvarez** [comment]
Fixed in most recent commit: https://github.com/danalvarez/gr-quetzal1/commit/fb4babd7bfabd52986e10a838762b09f52acb6c1. Turns out state of health needs no decode equation. Thanks!
